import ExcelJS from 'exceljs';

// Header keys are stable technical field names (not translated Uzbek
// phrases) so parsing-by-header-name (parsers/*.ts) never depends on
// locale — the template is generated by this same app, so producer and
// consumer always agree on these exact keys regardless of UI language (9.1
// trilingual UI applies to labels/messages shown to the user, not to a
// machine-readable header row we round-trip ourselves).
export const CUSTOMER_IMPORT_COLUMNS = [
  { header: 'code', key: 'code', width: 16 },
  { header: 'name', key: 'name', width: 32 },
  { header: 'phone', key: 'phone', width: 18 },
  { header: 'contactPerson', key: 'contactPerson', width: 24 },
  { header: 'paymentTermDays', key: 'paymentTermDays', width: 16 },
  { header: 'outletName', key: 'outletName', width: 24 },
  { header: 'outletAddress', key: 'outletAddress', width: 32 },
  { header: 'outletLatitude', key: 'outletLatitude', width: 16 },
  { header: 'outletLongitude', key: 'outletLongitude', width: 16 },
] as const;

const CUSTOMER_EXAMPLE_ROW = {
  code: 'C-0001',
  name: 'Do\'kon "Baraka"',
  phone: '+998901234567',
  contactPerson: 'Aziz Karimov',
  paymentTermDays: 14,
  outletName: 'Baraka do\'koni',
  outletAddress: 'Toshkent sh., Chilonzor tumani',
  outletLatitude: 41.2995,
  outletLongitude: 69.2401,
};

export const PRODUCT_IMPORT_COLUMNS = [
  { header: 'sku', key: 'sku', width: 16 },
  { header: 'name', key: 'name', width: 32 },
  { header: 'categoryName', key: 'categoryName', width: 24 },
  { header: 'brand', key: 'brand', width: 20 },
  { header: 'baseUnit', key: 'baseUnit', width: 14 },
  { header: 'vatRate', key: 'vatRate', width: 12 },
  { header: 'minPrice', key: 'minPrice', width: 14 },
  { header: 'barcode', key: 'barcode', width: 18 },
  { header: 'externalCode', key: 'externalCode', width: 16 },
] as const;

const PRODUCT_EXAMPLE_ROW = {
  sku: 'SKU-00001',
  name: 'Coca-Cola 0.5L',
  categoryName: 'Ichimliklar',
  brand: 'Coca-Cola',
  baseUnit: 'dona',
  vatRate: 12,
  minPrice: 4500,
  barcode: '4870001234567',
  externalCode: '',
};

async function buildTemplate(columns: readonly { header: string; key: string; width: number }[], exampleRow: object): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Import');
  sheet.columns = columns.map((c) => ({ header: c.header, key: c.key, width: c.width }));
  sheet.getRow(1).font = { bold: true };
  sheet.addRow(exampleRow);
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/** 9.2: "/import ... Shablon yuklab olish" — one example row shows the expected shape; the accountant deletes/replaces it before uploading. */
export function buildCustomersImportTemplate(): Promise<Buffer> {
  return buildTemplate(CUSTOMER_IMPORT_COLUMNS, CUSTOMER_EXAMPLE_ROW);
}

export function buildProductsImportTemplate(): Promise<Buffer> {
  return buildTemplate(PRODUCT_IMPORT_COLUMNS, PRODUCT_EXAMPLE_ROW);
}
